# This workflow will build a Swift project using the unified Makefile commands
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: 6.0.0 # Specify the required Swift version

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Integration Test
      run: make integration-test
